### PR TITLE
CloudMade ends 

### PR DESCRIPTION
**Pull request by flecno**
Hey,

CloudMade will discontinuing their tiles for non-enterprise users in next weeks, so let's move to other tile provider. With this change we can change to [Lzrk](https://geodienste.lyrk.de/) which provides 250.000 tile views per month for free to community (non-commercial) projects.

BTW: Pushing your API-Key to github isn't the best idea. Everyone knows best practices to handle this? This project doesn't contain every build process, so i don't know how to deploy this with gh-branches. Otherwise everbody can read the api key from the production source anywhere. Mhmm.

### CODE REVIEW

**Comment by andrenarchy** [comment]
Yeah, thx for bringing this up. We absolutely need to move to another tile server. Maybe we already hit the 250.000 tile limit but let's check.

In openwifimap's successor [libremap](https://github.com/libremap/libremap-webui), we have a [config file](https://github.com/libremap/libremap-webui/blob/master/config.json.example) for these purposes... here, it's directly included in the source. I agree that this is not optimal. Anyways, there's no way to hide your API key so I'd say we again include it in the source until everyone moved to libremap. ;)

@flecno: do you want to create an API key for lyrk and include it in your PR?

**Comment by flecno** [comment]
Oh, libremap looks interesting but so similar to openwifimap. What are the differences? Is it the further development of openwifimap?
I going to create a API key and update the PR

**Comment by andrenarchy** [comment]
thanks @flecno and sorry for the delay, I was a bit too busy in the last weeks. :smiley:

**Comment by flecno** [comment]
FYI: The limit of 250k tile requests are not realy reached:

lyrkgeodienste kundenmenu

**Comment by booo** [comment]
It's quite easy to setup a tile cache: http://wiki.openstreetmap.org/wiki/Tile_Proxy/squid

**Pull request merged**
